### ISSUE TITLE
What is jinja2-webpack-scan command?

### ISSUE THREAD

**Issue by mihalt** [JDeuce/python-jinja2-webpack#1]
Hi! Interesting lib. But I don't understand, how to use `jinja2-webpack-scan` command. What flags it has and what they are do? I have read the docs, and I can't understand difference between -d, -r, --reference-root? What do template positional argument do? Is it glob from root dir from -r which must take `.jinjia2` files? 

Help me please, because `webpack-asset-entries.js` don't contain anything and webpack don't see my `.jinjia2` modules.

**Comment by JDeuce** [comment]
Sounds like you may be looking for a project like https://github.com/pierreant-p/jinja-loader.
This project does not help you load .jinja2 modules into your webpack build.
What it does is allow you to reference other webpack assets from your jinja2 build.
So if you have a frontend which packs a bunch of assets with webpack, you can use your jinja2 backend in python to reference them with something like {{ 'mybundle.js' | webpack }} which would then get converted to say mybundle.HASH.js assuming you had webpack setup to output the bundle with a hash.

So this project has 2 parts. The part which lets you use statements like {{ 'mybundle.js' | webpack }} and then converts them to actual file references, and the scan part, which lets you identify all the things that your templates are referencing, and to possibly include those back into webpack

As for the usage of the scan:
--root (-r) specifies the root directory for the scan, so this is like the top level project directory.

--directories (-d) specifies a glob for directories within the root that contain templates

--reference-root is the root from which it should make all the requires() calls. The default for this is the directory of the output file (i.e. so if your output file is webpack/assets.js then all the imports in assets.js will be relative paths from the webpack/ directory)

- The positional arguments for templates are a glob from the root

The directories are passed into the FileSystemLoader from Jinja2 so that you can control which directories are loaded for the purpose of doing includes from other templates.

The simplest invocation from current directory would be:

`jinja2-webpack-scan -o webpack/output.js -d 'templates' 'templates/template1.jinja2'`
and if template1.jinja2 had a line like: `{{ 'mybundle.js' | webpack }}`
then it would generate an entry in output.js like `require('mybundle.js')`.

The scan part is a bit of a hack, but I do use it in production for awhile and it's been fine. The idea is that you could add output.js to the webpack build to make sure that it compiles any assets that you reference from Jinja2. Basically to close the loop with webpack to make sure it processes the files that jinja2 templates are referencing. If webpack is already generating the bundles you want to reference then you don't need the scan part at all.

**Comment by mihalt** [comment]
@JDeuce Hmm, ok. From your answer I understand that:
1. If I want to use Jinja2 templates I need in https://github.com/pierreant-p/jinja-loader and if I need correct end links to assets, I must use your lib. But as I understand jinja-loader have `require` filter which use the same, what do you `webpack` filter? Is it correct? 
2. About flags:
-r — as I see this way is relative on your example. Is from directrory where comand `jinja2-webpack-scan` is used? 
-d — why is it separated from `tepmplate` positional argument? As I unserstand, `template` is included it...

Is all right?

**Comment by JDeuce** [comment]
I'm not sure I understand question 1.

For the flags. Yeah by default the -r is from where you run the scan. If you want to use different directory as root you can pass it.

The directories argument is for configuring the jinja2 engine with extra directories. Say you want to scan the template templates/foo.jinja2 and inside foo.jinja2 it does an include for "bar.jinja2" which lives in the same folder. In that scenario you would want to use -d templates so that jinja2 knows it can look in templates to find things that are included, otherwise it might fail saying "bar.jinja2" could not be found.
